version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
  - dependency-name: mocha
    versions:
    - 8.3.0
  - dependency-name: knex
    versions:
    - 0.21.15
    - 0.21.17
