version: '2'

services:
  db:
    build:
      context: ./db
    image: integration-db
    ports:
      - 5432:5432

  project-service:
    image: ampnet/project-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
       - db
    ports:
       - 8123:8123

  wallet-service:
    image: ampnet/wallet-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
       - db
    ports:
       - 8128:8128

  blockchain-service:
    image: ampnet/crowdfunding-ae-middleware:latest
    environment:
      NODE_ENV: testnet
      GIFT_AMOUNT: 0
    depends_on:
      - db
    ports:
      - 8124:8124
      - 8224:8224

  user-service:
    image: ampnet/crowdfunding-user-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
      - db
    ports:
      - 8125:8125
  


  
