version: '3'

services:
  db:
    build:
      context: ./db
    image: integration-db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  project-service:
    image: ampnet/project-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
       - db
    ports:
       - 8123:8123

  wallet-service:
    image: ampnet/wallet-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
       - db
    ports:
       - 8128:8128

  blockchain-service:
    image: ampnet/crowdfunding-ae-middleware:latest
    environment:
      NODE_ENV: local
      NODE_URL: http://ae-node:3013
      NODE_INTERNAL_URL: http://ae-node:3113
      COMPILER_URL: http://sophia-compiler:3080
      NETWORK_ID: ae_docker
      COOP_OWNER: ak_fUq2NesPXcYZ1CcqBcGC3StpdnQw3iVxMA3YSeCNAwfN4myQk
      EUR_OWNER: ak_fUq2NesPXcYZ1CcqBcGC3StpdnQw3iVxMA3YSeCNAwfN4myQk
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ae_middleware_testnet
      DB_PASSWORD: password
      DB_NAME: ae_middleware_testnet
      QUEUE_DB_HOST: db
      QUEUE_DB_PORT: 5432
      QUEUE_DB_USER: ae_middleware_testnet_queue
      QUEUE_DB_PASSWORD: password
      QUEUE_DB_NAME: ae_middleware_testnet_queue
    restart: always
    depends_on:
      - db
      - ae-node
      - sophia-compiler
    ports:
      - 8124:8124
      - 8224:8224

  user-service:
    image: ampnet/user-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
      - db
    ports:
      - 8125:8125

  report-service:
    image: ampnet/report-service:latest
    environment:
      - "spring.profiles.active=dev"
    ports:
      - 8129:8129

  ae-node:
    image: aeternity/aeternity:v5.5.4
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    volumes:
      - ${PWD}/node/config/singlenode_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/config/accounts_test.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
    ports:
     - "3013:3013"
     - "3113:3113"
     - "3014:3014"

  sophia-compiler:
    image: aeternity/aesophia_http:v4.0.0
    ports:
       - "3080:3080"

  auto-funder:
    image: ampnet/auto-funder:latest
    environment:
      QUEUE_DB_HOST: db
      QUEUE_DB_PORT: 5432
      QUEUE_DB_USER: ae_middleware_testnet_queue
      QUEUE_DB_PASSWORD: password
      QUEUE_DB_NAME: ae_middleware_testnet_queue
      NODE_URL: http://ae-node:3013
      NODE_INTERNAL_URL: http://ae-node:3113
      COMPILER_URL: http://sophia-compiler:3080
      FUNDERS: 7c6e602a94f30e4ea7edabe4376314f69ba7eaa2f355ecedb339df847b6f0d80575f81ffb0a297b7725dc671da0b1769b1fc5cbe45385c7b5ad1fc2eaf1d609d
    restart: always
    depends_on:
      - ae-node
      - sophia-compiler
      - db
    ports:
      - "8130:8130"
