version: '3'

services:
  db:
    build:
      context: ./db
    image: integration-db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  project-service:
    image: ampnet/project-service:latest
    environment:
      - "spring.profiles.active=integration-test"
      - "com.ampnet.projectservice.image-proxy.url=http://localhost:8300"
    depends_on:
       - db
    ports:
       - 8123:8123

  wallet-service:
    image: ampnet/wallet-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
       - db
    ports:
       - 8128:8128

  blockchain-service:
    image: ampnet/crowdfunding-ae-middleware:latest
    environment:
      NODE_ENV: local
      NODE_URL: http://165.22.92.53:3013
      NODE_INTERNAL_URL: http://165.22.92.53:3113
      COMPILER_URL: http://sophia-compiler:3080
      NETWORK_ID: ampnet_private_network
      REDIS_HOST: redis
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ae_middleware_testnet
      DB_PASSWORD: password
      DB_NAME: ae_middleware_testnet
      WALLET_SERVICE_GRPC_URL: wallet-service:8228
      AMQP_URL: amqp://user:password@rabbitmq
    restart: always
    depends_on:
      - db
      - sophia-compiler
      - redis
    ports:
      - 8124:8124
      - 8224:8224

  user-service:
    image: ampnet/user-service:latest
    environment:
      - "spring.profiles.active=integration-test"
    depends_on:
      - db
    ports:
      - 8125:8125

  report-service:
    image: ampnet/report-service:latest
    environment:
      - "spring.profiles.active=dev"
    ports:
      - 8129:8129

  sophia-compiler:
    image: aeternity/aesophia_http:v4.3.2
    ports:
       - "3080:3080"

  auto-funder:
    image: ampnet/auto-funder:latest
    environment:
      NODE_URL: http://165.22.92.53:3013
      NODE_INTERNAL_URL: http://165.22.92.53:3113
      NETWORK_ID: ampnet_private_network
      COMPILER_URL: http://sophia-compiler:3080
      REDIS_HOST: redis
      FUNDERS: 707881878eacacce4db463de9c7bf858b95c3144d52fafed4a41ffd666597d0393d23cf31fcd12324cd45d4784d08953e8df8283d129f357463e6795b40e88aa
    restart: always
    depends_on:
      - sophia-compiler
      - db
      - redis
    ports:
      - "8130:8130"

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8-alpine
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  imgproxy:
    image: darthsim/imgproxy:v2.16
    environment:
      IMGPROXY_BIND: :8300
      IMGPROXY_ENFORCE_WEBP: 'true'
      IMGPROXY_KEY: 943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881
      IMGPROXY_SALT: 520f986b998545b4785e0defbc4f3c1203f22de2374a3d53cb7a7fe9fea309c5
    ports:
      - 8300:8300
